#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Shared data + path foundation for the SCORCH release scripts.

Sanitized, release-relative copy of the canonical
``scripts/six_task_review/common.py`` (research repository). ALL numeric
constants and algorithmic functions (canonical Method-A modal parameter
selection, event-day dedup table, rounding rule) are preserved VERBATIM;
only the path wiring changed (see docs/SANITIZATION_NOTES.md).

Input resolution (release layout, env-overridable):
    SCORCH_WORKBOOK  -> master catalog. Default is the deposit's master
                        catalog CSV (catalogs/scorch_new_algorithm_master_
                        cluster_ellipse_event_global_max.csv). For the
                        Tier-B master rebuild point this at the canonical
                        daily-adaptive workbook (.xlsx; NOT shipped in the
                        processed-data deposit).
    SCORCH_SELECTED_A-> per-day selected Method-A parameters CSV (Tier-B
                        artifact; NOT shipped -- regenerated by the full
                        pipeline or supplied via this variable).
    SCORCH_LABELS_A  -> per-day heatwave-labelled grid cell labels CSV. Default is the
                        deposit's global-max label file
                        (catalogs/final_labels_event_global_max.csv), which
                        carries the SAME per-day cell coordinates. To re-run
                        the Tier-B master build you must point this at the
                        daily-adaptive ``final_labels_method_A.csv``
                        (regenerated by the full pipeline).
    SCORCH_GRID_A    -> per-day eps x min_samples component grid
                        (shipped: data/auxiliary/method_a/
                        daily_full_parameter_grid_method_A.csv)
    SCORCH_OUT_BASE  -> root output dir (default: reproduced/six_task_review)
"""
from __future__ import annotations

import hashlib
import math
import os
import sys
from collections import Counter
from datetime import datetime, timezone

import numpy as np
import pandas as pd

# --- release wiring ----------------------------------------------------------
_THIS = os.path.abspath(__file__)
_COMMON_DIR = os.path.dirname(_THIS)
if _COMMON_DIR not in sys.path:
    sys.path.insert(0, _COMMON_DIR)

import _clean_paths as _cp  # noqa: E402

REPO_ROOT = _cp.RELEASE_ROOT

# --- canonical constants (VERBATIM from the research repository) -------------
SEED = 20260617
SIGMA = 1.25                       # canonical PCA ellipse scale
METHOD_A_EPS = [1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0]
MIN_SAMPLES = [4, 5, 6, 7, 8, 9, 10, 11, 12]
GRID_STEP = 1.0
NOISE = -1

WORKBOOK = os.environ.get(
    "SCORCH_WORKBOOK",
    _cp.data_file(
        "scorch_new_algorithm_master_cluster_ellipse_event_global_max.csv",
        "catalogs"))
WORKBOOK_SHEET = "master_cluster_ellipse"

# Precomputed canonical Method-A artifacts (produced by the full pipeline).
GRID_A_CSV = os.environ.get("SCORCH_GRID_A", os.path.join(
    _cp.AUX_DIR, "method_a", "daily_full_parameter_grid_method_A.csv"))
# Tier-B-only artifact: NOT shipped (regenerated by the full pipeline);
# override with SCORCH_SELECTED_A when available.
SELECTED_A_CSV = os.environ.get("SCORCH_SELECTED_A", os.path.join(
    _cp.AUX_DIR, "method_a", "daily_selected_parameters_method_A.csv"))
LABELS_A_CSV = os.environ.get("SCORCH_LABELS_A", _cp.LABELS_CSV)

# Output layout (everything under reproduced/)
OUT_BASE = os.environ.get(
    "SCORCH_OUT_BASE",
    os.path.join(_cp.GENERATED_DIR, "six_task_ellipse_review"))
GIF_DIR = os.environ.get("SCORCH_GIF_DIR",
                         os.path.join(_cp.GENERATED_DIR, "centroid_gifs"))
DOCS_DIR = os.path.join(_cp.GENERATED_DIR, "docs")
CONFIG_DIR = os.path.join(_cp.GENERATED_DIR, "config")

T01 = os.path.join(OUT_BASE, "task01_algorithm_and_parameter_audit")
T02 = os.path.join(OUT_BASE, "task02_snapshots_without_centroid_numbers")
T04 = os.path.join(OUT_BASE, "task04_global_event_parameter_validation")
T05 = os.path.join(OUT_BASE, "task05_parameter_heatmap_examples")
T06 = os.path.join(OUT_BASE, "task06_power_law")
QA_DIR = os.path.join(OUT_BASE, "qa")
REPORTS_DIR = os.path.join(OUT_BASE, "reports")

TYPE_NAMES = {1: "Independent", 2: "Spatially clustered",
              3: "Temporally clustered", 4: "Mixed"}


def ensure_dirs() -> None:
    for d in (T01, T02, T04, T05, T06,
              os.path.join(T06, "all_types_pooled"),
              os.path.join(T06, "by_type"),
              os.path.join(T06, "individual_type_diagnostics"),
              QA_DIR, REPORTS_DIR, GIF_DIR, DOCS_DIR):
        os.makedirs(d, exist_ok=True)


# --- hashing / versions ------------------------------------------------------
def sha256_file(path: str) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def utc_stamp() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def git_commit() -> str:
    import subprocess
    try:
        out = subprocess.run(["git", "rev-parse", "HEAD"], cwd=REPO_ROOT,
                             capture_output=True, text=True, timeout=15)
        return out.stdout.strip() or "unknown"
    except Exception:
        return "unknown"


def dependency_versions() -> dict:
    mods = {}
    for name in ("numpy", "pandas", "scipy", "sklearn", "matplotlib",
                 "openpyxl", "imageio", "PIL"):
        try:
            m = __import__(name)
            mods[name] = getattr(m, "__version__", "unknown")
        except Exception:
            mods[name] = "not-installed"
    mods["python"] = sys.version.split()[0]
    return mods


# --- workbook + tables -------------------------------------------------------
def load_workbook() -> pd.DataFrame:
    """Load the authoritative master table with parsed dates (read-only).

    Default is the deposit's master catalog CSV; an Excel workbook supplied
    via SCORCH_WORKBOOK (Tier-B daily-adaptive rebuild) is read from the
    canonical sheet.
    """
    if str(WORKBOOK).lower().endswith((".xlsx", ".xlsm", ".xls")):
        df = pd.read_excel(WORKBOOK, sheet_name=WORKBOOK_SHEET)
    else:
        df = pd.read_csv(WORKBOOK)
    df["date"] = pd.to_datetime(df["date"])
    return df


def build_event_day_table(df: pd.DataFrame | None = None) -> pd.DataFrame:
    """One row per unique (event, calendar day) with the day-level parameters.

    Verifies that repeated ellipse rows within an event-day agree on the
    selected EPS / min_samples and flags any that do not.
    """
    if df is None:
        df = load_workbook()
    rows = []
    for (eid, date), g in df.groupby(["new_event_id", "date"], sort=True):
        eps_vals = g["dbscan_avg_eps"].round(9).nunique()
        mp_vals = g["dbscan_rounded_minpts"].nunique()
        raw_vals = g["dbscan_raw_avg_minpts"].round(9).nunique()
        conflict = int(eps_vals > 1 or mp_vals > 1 or raw_vals > 1)
        rows.append(dict(
            new_event_id=int(eid),
            event_id=int(g["event_id"].iloc[0]),
            date=pd.Timestamp(date).strftime("%Y-%m-%d"),
            v3_type=int(g["v3_type"].iloc[0]),
            event_type=str(g["type"].iloc[0]),
            event_type_name=str(g["event_type_name"].iloc[0]),
            duration_days=int(g["duration_days"].iloc[0]),
            day_index_in_event=int(g["day_index_in_event"].iloc[0]),
            eps_selected=float(g["dbscan_avg_eps"].iloc[0]),
            min_samples_raw=float(g["dbscan_raw_avg_minpts"].iloc[0]),
            min_samples_selected=int(g["dbscan_rounded_minpts"].iloc[0]),
            modal_count=str(g["dbscan_modal_count"].iloc[0]),
            modal_count_max=max(_parse_int_set(g["dbscan_modal_count"].iloc[0])),
            is_modal_tie=int(len(_parse_int_set(g["dbscan_modal_count"].iloc[0])) > 1),
            n_ellipse_rows=int(g.shape[0]),
            n_unique_ellipses=int(g["cluster_id"].nunique()),
            day_final_n_clusters=int(g["day_final_n_clusters"].iloc[0]),
            source_sheet=WORKBOOK_SHEET,
            param_conflict_flag=conflict,
        ))
    out = pd.DataFrame(rows).sort_values(["date", "new_event_id"]).reset_index(
        drop=True)
    return out


# --- canonical Method-A selection (faithful copy of Phase 25 select_modal) ---
def _parse_int_set(val) -> list[int]:
    """Parse a modal-count cell that may be an int or a '1|2' tie string."""
    s = str(val).strip()
    if s in ("", "nan", "None"):
        return [0]
    out = []
    for tok in s.replace(",", "|").split("|"):
        tok = tok.strip()
        if tok and tok.lower() != "nan":
            try:
                out.append(int(float(tok)))
            except ValueError:
                pass
    return out or [0]


def round_half_up(x: float) -> int:
    return int(math.floor(float(x) + 0.5))


def select_modal(grid_rows: list[dict]) -> dict:
    """Modal-count selection with the canonical tie-averaging rule.

    grid_rows: list of dicts with keys 'eps', 'min_samples', 'n_components'.
    """
    counts = [r["n_components"] for r in grid_rows]
    nonzero = [c for c in counts if c > 0]
    pool = nonzero if nonzero else counts
    freq = Counter(pool)
    maxf = max(freq.values())
    tied = sorted([v for v, f in freq.items() if f == maxf])
    combos = [r for r in grid_rows if r["n_components"] in tied]
    avg_eps = float(np.mean([r["eps"] for r in combos]))
    raw_ms = float(np.mean([r["min_samples"] for r in combos]))
    rounded_ms = max(1, round_half_up(raw_ms))
    return dict(modal_counts=tied, n_modal_values=len(tied),
                is_tie=int(len(tied) > 1), modal_frequency=int(maxf),
                n_combos_averaged=len(combos),
                avg_eps=avg_eps, raw_avg_min_samples=raw_ms,
                rounded_min_samples=rounded_ms)


def load_grid_A() -> pd.DataFrame:
    """Per-day EPS x min_samples -> n_components (== n_ellipses) for Method A."""
    g = pd.read_csv(GRID_A_CSV)
    g["date"] = g["date"].astype(str)
    return g


def day_grid_rows(grid: pd.DataFrame, date: str) -> list[dict]:
    sub = grid[grid["date"] == str(date)]
    return [dict(eps=float(r.eps), min_samples=int(r.min_samples),
                 n_components=int(r.n_components))
            for r in sub.itertuples()]


def load_labels_A() -> pd.DataFrame:
    """Per-day heatwave-labelled grid cells with per-cell component labels."""
    df = pd.read_csv(LABELS_A_CSV)
    df["date"] = df["date"].astype(str)
    return df


def day_cells(labels: pd.DataFrame, date: str):
    """All exceedance-grid cell coordinates (lon, lat) for one day."""
    sub = labels[labels["date"] == str(date)]
    return sub["lon"].to_numpy(float), sub["lat"].to_numpy(float)


def write_manifest(path: str, payload: dict) -> None:
    import json
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as fh:
        json.dump(payload, fh, indent=2, default=str)
